# This file is licensed under the MIT License and is part of the "redirector" project.
# Copyright (c) 2019 Daniel Riegler
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# HTTP server settings
[http]

    # Default path prefix of the http server
    path = '/'

    # Default path of the api
    apiPath = '/api'

    # Port of the http server
    port = 5000

    # Host of the http server
    host = '127.0.0.1'

    # HTTP redirect settings
    [http.redirect]

        # Redirect status code
        status = 308

        # Default redirection (empty key)
        default = 'https://seeleft.de'

    # Authorization settings
    [http.authorization]

        # Authorization header name to use
        header = 'Authorization'

        # Expected value of the authorization header
        expect = 'YOUR_SAFE_TOKEN'

# Google recaptcha credentials
[recaptcha]

    site-key = ''
    secret-key = ''

# Database setings
[database]

    # pattern to match keys against
    key = '[A-Za-z0-9]{3,16}'

    # Type of the database
    # Currently available: mongodb
    type = ''

    # Database connection uri
    uri = ''

    # Database options (optional)
    options = {}